### PR TITLE
feat: update novelty sampler to work with pd.DataFrames

### PR DESCRIPTION
**Pull request by hollandjg**
with @blinodelka

### CODE REVIEW

**Review by musslick — CHANGES_REQUESTED** [review]
I'm not sure if we actually settled on using pd dataframe as standard output? My recollection was that we wanted to use numpy arrays since they are more familiar and easier to use. I think we should discuss...

**Comment by younesStrittmatter** [comment]
In the `novelty_score_sample` function, we append a score to the return value that is not part of the condition. Wrapping in the wrap_to_use_state would lead to an additional column in the condition field of the state. We should figure out a way to deal with functions that return additional things that are not part of a state field.

**Comment by hollandjg** [comment]
> We should figure out a way to deal with functions that return additional things that are not part of a state field.

This will conflict with the idea that the results of an experimentalist _have_ to have a spot on the State – sometimes they just need to be discarded.

**Comment by younesStrittmatter** [comment]
Or we make this explicit in the wrapper. If the user explicitly wants to discard return values from functions, they have to make that explicit when wrapping the function.

**Review by musslick — APPROVED** [review]
Looking good now!

**Pull request merged**
