### PR TITLE
update sampling function name

### LINKED ISSUE #12: update sampling function name
`novelty_sampler` --> `novelty_sample`

### PR DESCRIPTION
**Pull request by benwandrew**
fixes #12

### CODE REVIEW

**Comment by benwandrew** [comment]
@younesStrittmatter, i believe you had updated `novelty_score_sampler` but not `novelty_sampler`, so i just did (in __init__.py and Basic Usage.ipynb). let me know if this looks OK — thanks!

**Review by younesStrittmatter — APPROVED** [review]
looks good. Thank you!

**Comment by younesStrittmatter** [comment]
in the test files still the old names are used. We could change it or leave it for a later pull request.

**Comment by benwandrew** [comment]
> in the test files still the old names are used. We could change it or leave it for a later pull request.

good point! i will add to this PR. do you know if that is the case for other experimentalists as well -- ie, test files still need to be updated?

**Comment by younesStrittmatter** [comment]
neither the tests nor the examples are updated in the other experimentalists. I only updated the init files

**Comment by benwandrew** [comment]
> neither the tests nor the examples are updated in the other experimentalists. I only updated the init files

ok, i will add that to my list of things as i'm going through today

**Review by younesStrittmatter — APPROVED** [review]
looks good!

**Pull request merged**
